# Starship configuration file

[character]
success_symbol = "[âœ”ï¸](bold green)"
error_symbol = "[âœ˜](bold red)"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ”Œ"

[git_branch]
symbol = "ğŸŒ¿ "

[package]
symbol = "ğŸ“¦ "
